const actions = {
  SET_VIDEOS: "SET_VIDEOS",
  SET_CHANNELS: "SET_CHANNELS",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_SAVES: "SET_SAVES",
  CREATE_PLAYLIST: "CREATE_PLAYLIST",
  REMOVE_PLAYLIST: "REMOVE_PLAYLIST",
  ADD_TO_PLAYLIST: "ADD_TO_PLAYLIST",
  REMOVE_FROM_PLAYLIST: "REMOVE_FROM_PLAYLIST",
  ADD_TO_SAVE: "ADD_TO_SAVE",
  REMOVE_FROM_SAVE: "REMOVE_FROM_SAVE",
  TO_PLAYLIST_MODAL: "TO_PLAYLIST_MODAL",
  SET_USER_CREDENTIALS: "SET_USER_CREDENTIALS",
  REMOVE_USER_CREDENTIALS: "REMOVE_USER_CREDENTIALS",
  CLEAR_DATA: "CLEAR_DATA",
  SET_TOAST: "SET_TOAST",
  CLEAR_TOAST: "CLEAR_TOAST",
  SET_SHOW_TOAST: "SET_SHOW_TOAST",
  SET_TOAST_COLOR: "SET_TOAST_COLOR",
};

export { actions };
